import mongoose from "mongoose";

export const sample_foods = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Chicken Pizza",
    cookTime: "10-20",
    price: 15,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Chicken Biryani",
    price: 20,
    cookTime: "40-50",
    favorite: true,
    origins: ["Hyderabad", "South-India", "Asia"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["SlowFood", "Lunch", "Biryani"],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Chicken Burger",
    price: 9,
    cookTime: "10-15",
    favorite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Burger"],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "French Fries",
    price: 5,
    cookTime: "15-20",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["FastFood"],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Chicken Soup",
    price: 9,
    cookTime: "10-25",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Vegetables Pizza",
    price: 12,
    cookTime: "10-20",
    favorite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Burger", count: 1 },
  { name: "Biryani", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
];
